# Generated by Django 4.1.2 on 2022-10-24 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=70, unique=True)),
                ('slug', models.SlugField(max_length=70)),
                ('imagem', models.CharField(max_length=70)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('desconto', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'produto',
                'ordering': ('nome',),
            },
        ),
    ]
