# Generated by Django 4.1.2 on 2022-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=70)),
                ('pages_used', models.CharField(db_index=True, max_length=70)),
                ('short_description', models.CharField(db_index=True, max_length=70)),
            ],
            options={
                'db_table': 'card',
                'ordering': ('title',),
            },
        ),
    ]
