# Generated by Django 4.1.2 on 2022-10-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pages_used',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='card',
            name='short_description',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=70),
        ),
    ]
